using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Windows;

namespace McModpackTool.App.Services;

public sealed class LocalizationService : INotifyPropertyChanged
{
    private string _language = "zh_CN";
    public event PropertyChangedEventHandler? PropertyChanged;
    public event EventHandler? LanguageChanged;

    public string Language => _language;
    public string this[string key] => Translate(key);

    public void SetLanguage(string language, bool animate = true)
    {
        if (!Tables.ContainsKey(language)) language = "zh_CN";
        if (_language == language) return;
        _language = language;
        CultureInfo.CurrentUICulture = language switch
        {
            "zh_HK" => CultureInfo.GetCultureInfo("zh-HK"),
            "en_US" => CultureInfo.GetCultureInfo("en-US"),
            _ => CultureInfo.GetCultureInfo("zh-CN")
        };
        OnPropertyChanged("Item[]");
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Translate(string key, params object[] args)
    {
        string value = Tables.TryGetValue(_language, out var table) && table.TryGetValue(key, out string? localized)
            ? localized
            : Tables["zh_CN"].TryGetValue(key, out string? fallback) ? fallback : key;
        if (args.Length == 0) return value;
        try { return string.Format(CultureInfo.CurrentUICulture, value, args); }
        catch (FormatException) { return value; }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["zh_CN"] = new Dictionary<string, string>
            {
                ["app.name"] = "MC整合包工具", ["app.subtitle"] = "Minecraft 整合包工作台", ["app.short_subtitle"] = "工作台",
                ["window.minimize"] = "最小化", ["window.maximize_restore"] = "最大化或还原", ["window.close"] = "关闭",
                ["nav.home"] = "主页", ["nav.migration"] = "版本迁移", ["nav.client_pack"] = "客户端整合包打包", ["nav.server"] = "服务端一键打包", ["nav.settings"] = "设置",
                ["sidebar.collapse"] = "收起侧边栏", ["sidebar.expand"] = "展开侧边栏",
                ["home.title"] = "MC整合包工具", ["home.subtitle"] = "选择一个模块开始处理整合包",
                ["home.migration"] = "整合包版本迁移", ["home.migration.desc"] = "为 CurseForge / Modrinth 整合包匹配目标游戏版本",
                ["home.client_pack"] = "客户端整合包打包", ["home.client_pack.desc"] = "将 Minecraft 游戏目录导出为可安装的 CF / MR 客户端整合包",
                ["home.server"] = "服务端一键打包", ["home.server.desc"] = "将游戏目录或 CF / MR 整合包导出为可启动的服务器 ZIP",
                ["home.agreement"] = "用户协议", ["home.bilibili"] = "Bilibili 主页", ["home.github"] = "GitHub", ["author"] = "作者：风尘WD",
                ["home.creator"] = "风尘WD", ["home.creator_desc"] = "Minecraft/游戏区UP主及软件开发",
                ["migration.title"] = "整合包版本迁移", ["migration.subtitle"] = "CF/MR整合包目标游戏版本自动转换",
                ["migration.pack_file"] = "整合包文件", ["migration.choose_file"] = "选择文件", ["migration.read_pack"] = "读取整合包",
                ["migration.drop_title"] = "拖放整合包到这里", ["migration.drop_hint"] = "支持 .zip 和 .mrpack，松开后将自动读取",
                ["migration.source_overview"] = "源包概览", ["migration.target"] = "迁移目标", ["migration.loader"] = "加载器",
                ["migration.loader_version"] = "加载器版本", ["migration.latest_loader"] = "获取最新稳定版",
                ["migration.output_dir"] = "输出目录", ["migration.browse"] = "浏览", ["migration.output_name"] = "文件名 / 包名",
                ["migration.check"] = "开始分析", ["migration.analysis_hint"] = "请先导入并读取完整整合包，再点击此处分析。",
                ["migration.overview"] = "{0}\n\n平台格式    {1}\nMinecraft   {2}\n加载器      {3} {4}\n内容        {5} 个模组 · {6} 个资源包 · {7} 个光影包\n原样保留    overrides 中的全部文件（不查询、不迁移、不改写）",
                ["migration.report"] = "兼容性报告", ["migration.report_hint"] = "读取整合包后运行兼容性检查",
                ["migration.refresh"] = "重新分析", ["migration.files"] = "文件明细", ["migration.log"] = "运行日志",
                ["migration.ready"] = "就绪", ["migration.build"] = "生成新整合包",
                ["migration.new_pack"] = "新整合包", ["migration.migrated_suffix"] = "（已迁移）",
                ["tree.severity"] = "级别", ["tree.category"] = "类别", ["tree.item"] = "项目", ["tree.conclusion"] = "结论",
                ["tree.name"] = "名称", ["tree.source"] = "来源", ["tree.status"] = "状态", ["tree.output"] = "输出",
                ["category.mod"] = "模组", ["category.resourcepack"] = "资源包", ["category.shaderpack"] = "光影包",
                ["item_status.found"] = "已匹配", ["item_status.not_found"] = "未找到", ["item_status.preserved"] = "原样保留", ["item_status.pending"] = "待分析",
                ["item_status.passthrough"] = "直接转移", ["item_status.excluded"] = "已排除", ["item_status.disabled"] = "已禁用", ["item_status.warning"] = "警告",
                ["action.exclude"] = "排除", ["action.restore"] = "恢复", ["action.open"] = "打开页面",
                ["action.exclude_prompt"] = "是否从输出中排除“{0}”？", ["action.exclude_title"] = "排除内容项目",
                ["settings.title"] = "设置", ["settings.subtitle"] = "更改会立即生效并自动保存",
                ["settings.language"] = "语言", ["settings.language_desc"] = "选择软件界面的显示语言。",
                ["settings.appearance"] = "外观", ["settings.appearance_desc"] = "切换浅色、深色或跟随系统主题。",
                ["settings.light"] = "浅色", ["settings.dark"] = "深色", ["settings.system"] = "跟随系统",
                ["settings.accent"] = "主题颜色", ["settings.accent_desc"] = "选择按钮、侧边栏和选中状态使用的强调色。",
                ["settings.custom_color"] = "自定义颜色", ["settings.system_palette"] = "打开系统调色板", ["settings.color_rgb_invalid"] = "{0} 必须填写 0-255 之间的整数，请重新填写。", ["settings.color_hex_invalid"] = "HEX 颜色格式无效，请填写类似 #167D6A 的值。", ["settings.reset_color"] = "恢复默认",
                ["settings.font"] = "界面字体", ["settings.font_desc"] = "从这台电脑已安装的字体中选择。", ["settings.default_font"] = "系统默认", ["settings.font_preview"] = "MC整合包工具 · Minecraft 1.21.1",
                ["settings.about"] = "关于", ["settings.version"] = "版本号", ["settings.check_updates"] = "检查更新", ["settings.update_unavailable"] = "更新服务尚未开放。",
                ["client.title"] = "客户端整合包打包", ["client.subtitle"] = "从 Minecraft 游戏目录生成标准 CurseForge / Modrinth 客户端整合包",
                ["client.source_path"] = "游戏目录", ["client.choose_directory"] = "选择目录", ["client.read"] = "读取内容",
                ["client.source_hint"] = "仅支持文件夹导入；请选择包含 mods、config、saves 等内容的游戏目录或版本隔离实例。",
                ["client.source_overview"] = "目录概览", ["client.environment"] = "客户端环境", ["client.loader"] = "模组加载器",
                ["client.content"] = "导出内容", ["client.content_hint"] = "父级复选框可控制整个分组；目录项目会完整复制，不会展开为大量内部文件。",
                ["client.restore_defaults"] = "恢复默认选择", ["client.clear_all"] = "全部取消",
                ["client.output"] = "导出设置", ["client.formats"] = "整合包格式", ["client.output_dir"] = "输出目录", ["client.output_name"] = "整合包名称", ["client.browse"] = "浏览",
                ["client.log"] = "运行日志", ["client.ready"] = "就绪", ["client.reading"] = "正在读取客户端内容…", ["client.read_ready"] = "内容读取完成，可选择项目并生成整合包", ["client.path_changed"] = "输入路径已更改，请重新读取内容", ["client.cancelled"] = "操作已取消",
                ["client.build"] = "生成客户端整合包", ["client.building"] = "正在生成客户端整合包…", ["client.building_match"] = "正在按文件哈希匹配 CF / MR 下载项…", ["client.building_copy"] = "正在复制本地内容与未识别文件…", ["client.building_manifest"] = "正在写入整合包清单…", ["client.building_archive"] = "正在压缩整合包…", ["client.build_complete"] = "客户端整合包导出成功", ["client.build_partial"] = "部分格式已导出，另有格式生成失败",
                ["client.overview"] = "{0}\n\nMinecraft   {1}\n加载器      {2} {3}\n内容项目    {4} 个\n当前选中    {5} 个",
                ["client.group_summary"] = "{0} 项 · {1}", ["client.group.expand"] = "展开此分类", ["client.group.collapse"] = "折叠此分类",
                ["client.group.mod"] = "模组", ["client.group.resource_pack"] = "材质包", ["client.group.shader_pack"] = "光影包", ["client.group.world"] = "地图与存档",
                ["client.group.configuration"] = "Mod 与游戏配置", ["client.group.mod_data"] = "小地图、世界地图及其他 Mod 数据", ["client.group.options"] = "游戏设置 (options.txt)", ["client.group.server_list"] = "多人游戏服务器列表",
                ["client.group.screenshot"] = "截图", ["client.group.structure"] = "投影与结构文件", ["client.group.replay"] = "录像与回放", ["client.group.command_history"] = "命令历史", ["client.group.hotbar"] = "快捷栏", ["client.group.other"] = "其他模组数据",
                ["client.dialog.choose_directory"] = "选择 Minecraft 游戏目录或版本隔离实例", ["client.dialog.reselect_instance"] = "所选目录下没有可读取的客户端内容。请重新选择 .minecraft\\versions\\对应版本的实例目录。", ["client.dialog.no_version"] = "没有从标准版本 JSON 中识别到 Minecraft 版本和加载器。", ["client.dialog.read_failed"] = "读取失败。请确认已选择有效的 Minecraft 游戏目录，并查看运行日志。", ["client.dialog.read_first"] = "请先选择并读取 Minecraft 游戏目录。",
                ["client.dialog.format_required"] = "至少需要选择一种整合包格式。", ["client.dialog.content_required"] = "请至少选择一个要导出的内容项目。", ["client.dialog.output_invalid"] = "请填写有效的输出目录和整合包名称。", ["client.dialog.build_failed"] = "生成客户端整合包失败。请检查网络、文件权限和运行日志。", ["client.dialog.build_failed_detail"] = "部分整合包未能生成：\n\n{0}",
                ["server.title"] = "服务端一键打包", ["server.subtitle"] = "从游戏目录或标准 CF / MR 整合包生成完整可启动的服务器 ZIP",
                ["server.source_type"] = "导入方式", ["server.directory"] = "文件夹", ["server.modpack"] = "整合包",
                ["server.source_path"] = "游戏目录", ["server.pack_path"] = "整合包文件", ["server.choose_directory"] = "选择目录", ["server.choose_pack"] = "选择文件", ["server.read"] = "读取内容",
                ["server.drop_title"] = "拖放整合包到这里", ["server.drop_hint"] = "仅整合包模式支持拖放 .zip 或 .mrpack",
                ["server.source_overview"] = "源内容", ["server.environment"] = "服务端环境", ["server.minecraft"] = "Minecraft", ["server.loader"] = "模组加载器", ["server.loader_version"] = "加载器版本", ["server.java"] = "Java 运行时", ["server.java_hint"] = "读取内容后将结合游戏版本和已选模组声明，自动选择已安装的 Java。",
                ["server.version_hint"] = "游戏版本由导入内容决定；服务端一键打包不支持版本迁移。",
                ["server.core"] = "服务器核心", ["server.core_refresh"] = "刷新可用核心", ["server.core_none"] = "尚未查询到可用核心", ["server.core_hint"] = "只显示官方元数据确认支持当前游戏版本的核心。",
                ["server.content"] = "导出内容", ["server.mods"] = "模组", ["server.select_all"] = "全选", ["server.clear_all"] = "清空", ["server.mod_name"] = "名称", ["server.mod_path"] = "相对路径", ["server.mod_support"] = "服务端适用性", ["server.mod_source"] = "来源",
                ["server.config"] = "Mod 配置 (config)", ["server.defaultconfigs"] = "默认配置 (defaultconfigs)", ["server.kubejs"] = "KubeJS 脚本与数据", ["server.scripts"] = "脚本目录 (scripts)",
                ["server.world"] = "服务端存档", ["server.no_world"] = "不导入存档", ["server.world_hint"] = "选中的存档会完整复制并重命名为 world。",
                ["server.output"] = "导出设置", ["server.output_dir"] = "输出目录", ["server.output_name"] = "文件名", ["server.browse"] = "浏览", ["server.prepare"] = "开始准备", ["server.build"] = "生成服务器 ZIP",
                ["server.log"] = "运行日志", ["server.ready"] = "就绪", ["server.reading"] = "正在读取输入内容…", ["server.preparing"] = "正在检查模组并匹配服务器核心…", ["server.building"] = "正在生成服务器 ZIP…", ["server.prepared"] = "准备完成，可以生成服务器 ZIP", ["server.cancelled"] = "操作已取消",
                ["server.building_core"] = "正在下载并安装服务端核心…", ["server.building_mods_copy"] = "正在复制 MOD…", ["server.building_mods_download"] = "正在下载 MOD…", ["server.building_config"] = "正在复制服务端配置…", ["server.building_world"] = "正在复制存档…", ["server.building_files"] = "正在生成服务端启动文件…", ["server.building_archive"] = "正在压缩服务器 ZIP…", ["server.download_speed"] = "下载速度：{0}",
                ["server.overview"] = "{0}\n\n来源        {1}\nMinecraft   {2}\n加载器      {3} {4}\n模组        {5} 个\n存档        {6} 个",
                ["server.support.recommended"] = "推荐", ["server.support.optional"] = "可选", ["server.support.unsupported"] = "不支持服务端", ["server.support.unknown"] = "未知", ["server.origin.manifest"] = "下载清单", ["server.origin.local"] = "本地文件",
                ["server.dialog.choose_directory"] = "选择 Minecraft 游戏目录或版本隔离实例", ["server.dialog.reselect_instance"] = "所选目录下没有可读取的 mods、config、saves 等内容。请重新选择 .minecraft\\versions\\对应版本的实例目录。",
                ["server.dialog.no_version"] = "没有从标准版本 JSON 中识别到 Minecraft 版本和加载器。", ["server.dialog.quilt"] = "服务端一键打包暂不支持 Quilt。", ["server.dialog.read_failed"] = "读取失败。请确认路径或整合包格式正确，并查看运行日志。",
                ["server.dialog.prepare_first"] = "请先读取内容并完成准备。", ["server.dialog.core_required"] = "请选择一个当前游戏版本可用的服务器核心。", ["server.dialog.source_version_missing"] = "导入内容中没有可用的 Minecraft 版本信息，请重新选择有效的游戏目录或整合包。", ["server.dialog.output_invalid"] = "请填写有效的输出目录和 ZIP 文件名。",
                ["server.dialog.vanilla"] = "该核心为原版核心，该服务端不可加载任何模组及插件，不能作为模组服务端使用。是否继续？", ["server.dialog.eula"] = "是否同意 Minecraft EULA？\n\n选择“是”会写入 eula=true；选择“否”会写入 eula=false。",
                ["server.dialog.choose_java"] = "选择用于服务器的 java.exe", ["server.dialog.java_required"] = "未选择可用的 Java 运行时。请重新读取内容或选择合适的 Java。", ["server.dialog.java_none"] = "未检测到可用的 Java。请先安装 Java {0}，然后重新读取内容。", ["server.dialog.java_incompatible"] = "Minecraft {0} 与当前已选模组要求使用 Java {1}，当前选择的是 Java {2}。为避免服务器启动失败，请选择 Java {1}。",
                ["server.dialog.incompatible"] = "“{0}”存在阻断兼容性问题：\n\n{1}\n\n是否从输出中排除此项？\n\n选择“否”将保留该模组并继续导出。",
                ["server.dialog.blocked"] = "服务端 ZIP 未生成，仍有文件无法下载或写入：\n\n{0}", ["server.dialog.build_failed"] = "生成服务器 ZIP 失败。请检查网络、Java 环境和输出权限，并查看运行日志。", ["server.build_complete"] = "服务端 ZIP 导出成功", ["server.build_launch_hint"] = "启动服务器时，可双击 start.bat；也可右键 server-console.ps1 并选择“使用 PowerShell 运行”，两者作用相同。控制台会用不同颜色突出警告、错误和启动成功状态。",
                ["server.version_select_title"] = "选择游戏版本", ["server.version_select_hint"] = "该目录包含多个标准版本 JSON，请选择要导出的实例版本。",
                ["agreement.title"] = "用户协议与使用须知", ["agreement.language"] = "协议语言", ["agreement.code_license"] = "查看代码许可（PolyForm NC 1.0.0）", ["agreement.asset_license"] = "查看美术与文档许可（CC BY-NC-SA 4.0）", ["agreement.third_party"] = "查看第三方许可", ["agreement.third_party_title"] = "第三方许可与通知",
                ["agreement.accept"] = "我已阅读并同意", ["agreement.decline"] = "不同意并退出", ["agreement.close"] = "关闭",
                ["common.ok"] = "确定", ["common.cancel"] = "取消", ["common.yes"] = "是", ["common.no"] = "否",
                ["common.error"] = "错误", ["common.warning"] = "提示", ["common.processing"] = "处理中…",
                ["app.unhandled_error"] = "程序遇到未处理的错误。\n\n{0}", ["app.agreement_save_failed"] = "无法保存用户协议同意状态，软件将退出。\n\n{0}",
                ["dialog.choose_pack"] = "选择整合包文件", ["dialog.choose_output"] = "选择输出目录",
                ["dialog.filter_modpacks"] = "整合包", ["dialog.filter_all"] = "所有文件",
                ["dialog.invalid_pack"] = "仅支持 .zip 或 .mrpack 整合包文件。", ["dialog.drop_failed"] = "无法读取拖放的文件，请使用“选择文件”重试并查看运行日志。", ["dialog.busy"] = "当前正在处理，请稍候。",
                ["dialog.read_first"] = "请先读取整合包。", ["dialog.target_required"] = "请填写完整的目标游戏版本、加载器和加载器版本。",
                ["dialog.analysis_first"] = "生成前请先完成兼容性分析。", ["dialog.overwrite"] = "目标文件已存在，是否覆盖？",
                ["dialog.no_loader_version"] = "未能取得对应加载器的稳定版本。", ["dialog.output_is_input"] = "输出文件不能覆盖当前导入的整合包。",
                ["dialog.output_invalid"] = "请填写有效的输出目录和文件名。", ["dialog.output_invalid_chars"] = "输出文件名包含无效字符。",
                ["dialog.read_failed"] = "读取整合包失败。请确认文件未损坏且格式正确，并查看运行日志。", ["dialog.analysis_failed"] = "兼容性分析失败。请检查网络连接后重试，并查看运行日志。",
                ["dialog.settings_fonts_failed"] = "无法读取系统字体列表，请稍后重试。", ["dialog.settings_save_failed"] = "设置未能保存，本次更改可能不会在下次启动时保留。", ["dialog.agreement_language_save_failed"] = "用户协议语言偏好未能保存。", ["dialog.open_folder_failed"] = "无法打开导出文件所在文件夹。",
                ["build.complete"] = "整合包导出成功", ["build.open_folder"] = "打开导出文件夹",
                ["build.notice"] = "整合包导出成功！可能仍存在部分模组及前置版本冲突或不符合，软件还在持续开发中，带来不便尽情谅解",
                ["build.location"] = "保存位置：{0}", ["build.failed"] = "生成整合包失败。请检查输出路径、文件权限和网络连接，并查看运行日志。", ["build.notes"] = "注意事项：",
                ["build.item"] = "{0} [{1}]", ["build.disabled_item"] = "[禁用] {0}",
                ["build.reason.override_collision"] = "{0}（与 overrides 现有文件同名，未覆盖原文件）", ["build.reason.env_scope"] = "{0}（无法保留 env 作用域）",
                ["build.warning.cf_override_collision"] = "{0}：目标路径与 overrides 现有文件同名，已保留原文件并使用联网安装引用。",
                ["build.warning.mr_override_collision"] = "{0}：目标路径与 overrides 现有文件同名，已保留原文件和联网安装引用。",
                ["build.warning.cf_download_fallback"] = "{0}：下载失败，已回退为 CurseForge 联网安装引用。", ["build.warning.cf_no_download"] = "{0}：平台未提供下载地址，已保留 CurseForge 联网安装引用。",
                ["build.warning.mr_env_reference"] = "{0}：为保留 Modrinth env 作用域，已保留联网安装引用。", ["build.warning.mr_download_fallback"] = "{0}：下载失败，已回退为 Modrinth 联网安装引用。",
                ["build.warning.disabled_download_preserved"] = "[禁用] {0}：目标下载失败，已保留旧禁用版本。", ["build.warning.disabled_no_target_preserved"] = "[禁用] {0}：未找到目标版本，已保留旧禁用版本。",
                ["build.incomplete_status"] = "整合包未导出",
                ["build.incomplete"] = "整合包未导出：仍有 {0} 个文件无法写入。请排除这些项目或检查网络后重试。\n\n{1}",
                ["resolution.not_found"] = "“{0}”没有对应的目标版本。是否将其从输出中排除？\n\n选择“否”会暂时忽略，但导出前仍需排除。",
                ["resolution.incompatible"] = "“{0}”存在阻断兼容性问题：\n\n{1}\n\n是否从输出中排除此项？",
                ["resolution.duplicate"] = "“{0}”使用了重复输出路径“{1}”。是否排除？",
                ["resolution.unmapped"] = "以下阻断问题无法自动定位到可排除的模组，请返回列表调整选择后重试：\n\n{0}",
                ["resolution.blocked"] = "仍有 {0} 项阻断问题未处理。存在阻断问题时无法导出。",
                ["deps.title"] = "可能缺少前置模组", ["deps.body"] = "平台元数据显示可能缺少以下必需依赖。工具不会自动修改列表，请自行核对：\n\n{0}\n\n该信息为工具根据平台数据提示，仅供参考。",
                ["deps.entry"] = "{0}（{1}；由 {2} 声明）", ["deps.more_owners"] = " 等 {0} 个项目", ["deps.more"] = "... 以及其他 {0} 个可能缺少的前置模组",
                ["status.reading"] = "正在读取整合包…", ["status.read_ready"] = "已读取整合包，请确认目标设置后开始分析",
                ["status.searching"] = "正在查询目标版本…", ["status.analyzing"] = "正在生成兼容性报告…",
                ["status.ready_build"] = "兼容性分析完成，可以生成新整合包", ["status.building"] = "正在生成整合包…",
                ["status.canceling"] = "正在取消…", ["status.cancelled"] = "操作已取消", ["status.analysis_failed"] = "分析失败，请重试", ["status.loader_fetching"] = "正在获取加载器版本…", ["status.target_changed"] = "迁移目标已更改，请重新分析",
                ["compat.no_issues"] = "未发现可静态确认的阻断或警告。", ["compat.summary"] = "{0} 项阻断 · {1} 项警告 · {2} 个内容项目",
                ["compat.error"] = "阻断", ["compat.warning"] = "警告", ["compat.info"] = "信息",
                ["compat.boundary"] = "边界", ["compat.static_check"] = "静态检查", ["compat.whole"] = "整体", ["compat.pack"] = "整合包", ["compat.pass"] = "通过",
                ["compat.loader_dependency_mismatch"] = "加载器版本不符合模组声明的依赖要求。",
                ["compat.scope.mod"] = "模组", ["compat.scope.resourcepack"] = "资源包", ["compat.scope.shaderpack"] = "光影包", ["compat.scope.content"] = "内容", ["compat.scope.dependency"] = "依赖", ["compat.scope.output"] = "输出", ["compat.scope.general"] = "通用",
                ["compat.issue.item_not_found"] = "未找到目标版本文件。", ["compat.issue.missing_required_dependency"] = "可能缺少必需前置模组：{0}。",
                ["compat.issue.dependency_version_mismatch"] = "前置模组版本不符合所需范围。", ["compat.issue.loader_version_mismatch"] = "加载器版本不符合模组要求。", ["compat.issue.loader_dependency_mismatch"] = "加载器版本不符合模组声明的依赖要求。", ["compat.issue.minecraft_version_mismatch"] = "Minecraft 版本不符合模组要求。",
                ["compat.issue.explicit_incompatibility"] = "与已选项目或目标环境“{0}”明确冲突。", ["compat.issue.explicitly_incompatible_item"] = "平台或模组元数据明确标记此项目不兼容。",
                ["compat.issue.duplicate_project"] = "同一平台项目出现多次。", ["compat.issue.duplicate_output_path"] = "多个文件将写入同一个输出路径。",
                ["compat.issue.unsafe_output_path"] = "目标文件路径无效或可能越出整合包目录。", ["compat.issue.unsafe_override_path"] = "overrides 中存在不安全或大小写冲突的路径。", ["compat.issue.override_output_collision"] = "目标文件与 overrides 中的现有文件同名；为保证原文件不变，已阻止覆盖。",
                ["compat.issue.required_embedded_download_unavailable"] = "此 CurseForge 项目必须嵌入 Modrinth 包，但平台未提供可下载地址。", ["compat.issue.required_embedded_scope_unsupported"] = "此 CurseForge 项目必须嵌入，但原 Modrinth 客户端/服务端作用域无法安全保留。",
                ["compat.issue.dependency_version_unverified"] = "无法静态确认依赖版本范围。", ["compat.issue.incompatibility_version_unverified"] = "无法静态确认冲突版本范围。", ["compat.issue.unknown"] = "检测到未分类的兼容性问题，请查看问题代码和依据。",
                ["compat.limit.runtime"] = "静态检查无法验证模组字节码、Mixin、注册表、数据包及仅在运行时出现的冲突。",
                ["compat.limit.relations"] = "只检查可识别的直接必需依赖、明确冲突和受支持的版本条件；不会验证递归依赖或跨平台项目身份。",
                ["compat.limit.metadata"] = "{0} / {1} 个已解析项目缺少依赖/冲突元数据，无法静态确认其前置与明确冲突。",
                ["compat.limit.java"] = "迁移目标未指定 Java 运行时版本，因此未检查模组声明的 Java 要求。",
                ["compat.limit.artifact"] = "“{0}”的文件元数据不完整：{1}",
                ["compat.limit.artifact_multiple"] = "存在多个“{0}”元数据文件，无法确定应使用哪一个。", ["compat.limit.artifact_read"] = "无法读取元数据文件“{0}”。", ["compat.limit.artifact_parse"] = "无法解析元数据文件“{0}”。", ["compat.limit.artifact_unknown"] = "元数据检查返回了未分类警告。",
                ["detail.code"] = "代码", ["detail.confidence"] = "置信度", ["detail.path"] = "路径", ["detail.evidence"] = "依据",
                ["log.read_pack"] = "读取整合包：{0}", ["log.read_complete"] = "读取完成：format={0}, items={1}, overrides={2}", ["log.read_cancelled"] = "读取操作已取消",
                ["log.loader_latest"] = "{0} {1} 最新稳定版：{2}", ["log.analysis_start"] = "开始查询目标：Minecraft {0}, {1}",
                ["log.analysis_complete"] = "目标查询完成：found={0}, preserved={1}, missing={2}", ["log.analysis_cancelled"] = "分析操作已取消", ["log.build_complete"] = "整合包导出完成：{0}",
                ["log.excluded"] = "已从输出排除：{0}", ["log.restored"] = "已恢复到输出：{0}",
                ["note.preserved"] = "目标环境未变化，保留原文件", ["note.no_cf_key"] = "未配置 CurseForge API Key，已跳过备用搜索",
                ["note.prerelease"] = "只有预发布版本（{0}）", ["note.project_missing"] = "平台项目或版本不存在",
                ["note.invalid_cf_id"] = "CurseForge 项目 ID 无效", ["note.no_target"] = "原项目没有可用的目标版本",
                ["note.identity_unverified"] = "无法验证原项目文件身份", ["note.no_confident_match"] = "没有高置信度的平台身份匹配",
                ["note.no_main_file"] = "目标版本缺少可用主文件"
            },
            ["zh_HK"] = new Dictionary<string, string>
            {
                ["app.name"] = "MC整合包工具", ["app.subtitle"] = "Minecraft 整合包工作台", ["app.short_subtitle"] = "工作台",
                ["window.minimize"] = "最小化", ["window.maximize_restore"] = "最大化或還原", ["window.close"] = "關閉",
                ["nav.home"] = "主頁", ["nav.migration"] = "版本遷移", ["nav.client_pack"] = "客戶端整合包封裝", ["nav.server"] = "伺服器一鍵封裝", ["nav.settings"] = "設定",
                ["sidebar.collapse"] = "收起側邊欄", ["sidebar.expand"] = "展開側邊欄",
                ["home.title"] = "MC整合包工具", ["home.subtitle"] = "選擇一個模組開始處理整合包",
                ["home.migration"] = "整合包版本遷移", ["home.migration.desc"] = "為 CurseForge / Modrinth 整合包配對目標遊戲版本",
                ["home.client_pack"] = "客戶端整合包封裝", ["home.client_pack.desc"] = "將 Minecraft 遊戲目錄匯出為可安裝的 CF / MR 客戶端整合包",
                ["home.server"] = "伺服器一鍵封裝", ["home.server.desc"] = "將遊戲目錄或 CF / MR 整合包匯出為可啟動的伺服器 ZIP",
                ["home.agreement"] = "用戶協議", ["home.bilibili"] = "Bilibili 主頁", ["home.github"] = "GitHub", ["author"] = "作者：风尘WD",
                ["home.creator"] = "风尘WD", ["home.creator_desc"] = "Minecraft／遊戲區 UP 主及軟件開發",
                ["migration.title"] = "整合包版本遷移", ["migration.subtitle"] = "CF/MR 整合包目標遊戲版本自動轉換",
                ["migration.pack_file"] = "整合包檔案", ["migration.choose_file"] = "選擇檔案", ["migration.read_pack"] = "讀取整合包",
                ["migration.drop_title"] = "將整合包拖放到這裡", ["migration.drop_hint"] = "支援 .zip 及 .mrpack，放開後會自動讀取",
                ["migration.source_overview"] = "來源包概覽", ["migration.target"] = "遷移目標", ["migration.loader"] = "載入器",
                ["migration.loader_version"] = "載入器版本", ["migration.latest_loader"] = "取得最新穩定版",
                ["migration.output_dir"] = "輸出資料夾", ["migration.browse"] = "瀏覽", ["migration.output_name"] = "檔案名稱 / 包名",
                ["migration.check"] = "開始分析", ["migration.analysis_hint"] = "請先匯入並讀取完整整合包，再按此處分析。",
                ["migration.overview"] = "{0}\n\n平台格式    {1}\nMinecraft   {2}\n載入器      {3} {4}\n內容        {5} 個模組 · {6} 個資源包 · {7} 個光影包\n原樣保留    overrides 中的全部檔案（不查詢、不遷移、不改寫）",
                ["migration.report"] = "兼容性報告", ["migration.report_hint"] = "讀取整合包後執行兼容性檢查",
                ["migration.refresh"] = "重新分析", ["migration.files"] = "檔案明細", ["migration.log"] = "運行記錄",
                ["migration.ready"] = "就緒", ["migration.build"] = "產生新整合包",
                ["migration.new_pack"] = "新整合包", ["migration.migrated_suffix"] = "（已遷移）",
                ["tree.severity"] = "級別", ["tree.category"] = "類別", ["tree.item"] = "項目", ["tree.conclusion"] = "結論",
                ["tree.name"] = "名稱", ["tree.source"] = "來源", ["tree.status"] = "狀態", ["tree.output"] = "輸出",
                ["category.mod"] = "模組", ["category.resourcepack"] = "資源包", ["category.shaderpack"] = "光影包",
                ["item_status.found"] = "已配對", ["item_status.not_found"] = "未找到", ["item_status.preserved"] = "原樣保留", ["item_status.pending"] = "待分析",
                ["item_status.passthrough"] = "直接轉移", ["item_status.excluded"] = "已排除", ["item_status.disabled"] = "已停用", ["item_status.warning"] = "警告",
                ["action.exclude"] = "排除", ["action.restore"] = "復原", ["action.open"] = "開啟頁面",
                ["action.exclude_prompt"] = "是否從輸出中排除「{0}」？", ["action.exclude_title"] = "排除內容項目",
                ["settings.title"] = "設定", ["settings.subtitle"] = "變更會立即生效並自動儲存",
                ["settings.language"] = "語言", ["settings.language_desc"] = "選擇軟件介面的顯示語言。",
                ["settings.appearance"] = "外觀", ["settings.appearance_desc"] = "切換淺色、深色或跟隨系統主題。",
                ["settings.light"] = "淺色", ["settings.dark"] = "深色", ["settings.system"] = "跟隨系統",
                ["settings.accent"] = "主題顏色", ["settings.accent_desc"] = "選擇按鈕、側邊欄及選取狀態使用的強調色。",
                ["settings.custom_color"] = "自訂顏色", ["settings.system_palette"] = "開啟系統調色盤", ["settings.color_rgb_invalid"] = "{0} 必須填寫 0-255 之間的整數，請重新填寫。", ["settings.color_hex_invalid"] = "HEX 顏色格式無效，請填寫類似 #167D6A 的值。", ["settings.reset_color"] = "回復預設",
                ["settings.font"] = "介面字體", ["settings.font_desc"] = "從這部電腦已安裝的字體中選擇。", ["settings.default_font"] = "系統預設", ["settings.font_preview"] = "MC整合包工具 · Minecraft 1.21.1",
                ["settings.about"] = "關於", ["settings.version"] = "版本號", ["settings.check_updates"] = "檢查更新", ["settings.update_unavailable"] = "更新服務尚未開放。",
                ["client.title"] = "客戶端整合包封裝", ["client.subtitle"] = "從 Minecraft 遊戲目錄產生標準 CurseForge / Modrinth 客戶端整合包",
                ["client.source_path"] = "遊戲目錄", ["client.choose_directory"] = "選擇目錄", ["client.read"] = "讀取內容",
                ["client.source_hint"] = "僅支援資料夾匯入；請選擇包含 mods、config、saves 等內容的遊戲目錄或版本隔離實例。",
                ["client.source_overview"] = "目錄概覽", ["client.environment"] = "客戶端環境", ["client.loader"] = "模組載入器",
                ["client.content"] = "匯出內容", ["client.content_hint"] = "父級核取方塊可控制整個分組；目錄項目會完整複製，不會展開為大量內部檔案。",
                ["client.restore_defaults"] = "恢復預設選擇", ["client.clear_all"] = "全部取消",
                ["client.output"] = "匯出設定", ["client.formats"] = "整合包格式", ["client.output_dir"] = "輸出目錄", ["client.output_name"] = "整合包名稱", ["client.browse"] = "瀏覽",
                ["client.log"] = "執行記錄", ["client.ready"] = "就緒", ["client.reading"] = "正在讀取客戶端內容…", ["client.read_ready"] = "內容讀取完成，可選擇項目並產生整合包", ["client.path_changed"] = "輸入路徑已變更，請重新讀取內容", ["client.cancelled"] = "操作已取消",
                ["client.build"] = "產生客戶端整合包", ["client.building"] = "正在產生客戶端整合包…", ["client.building_match"] = "正在按檔案雜湊配對 CF / MR 下載項目…", ["client.building_copy"] = "正在複製本機內容與未識別檔案…", ["client.building_manifest"] = "正在寫入整合包清單…", ["client.building_archive"] = "正在壓縮整合包…", ["client.build_complete"] = "客戶端整合包匯出成功", ["client.build_partial"] = "部分格式已匯出，另有格式產生失敗",
                ["client.overview"] = "{0}\n\nMinecraft   {1}\n載入器      {2} {3}\n內容項目    {4} 個\n目前選取    {5} 個",
                ["client.group_summary"] = "{0} 項 · {1}", ["client.group.expand"] = "展開此分類", ["client.group.collapse"] = "摺疊此分類",
                ["client.group.mod"] = "模組", ["client.group.resource_pack"] = "材質包", ["client.group.shader_pack"] = "光影包", ["client.group.world"] = "地圖與存檔",
                ["client.group.configuration"] = "Mod 與遊戲設定", ["client.group.mod_data"] = "小地圖、世界地圖及其他 Mod 資料", ["client.group.options"] = "遊戲設定 (options.txt)", ["client.group.server_list"] = "多人遊戲伺服器列表",
                ["client.group.screenshot"] = "截圖", ["client.group.structure"] = "投影與結構檔案", ["client.group.replay"] = "錄影與重播", ["client.group.command_history"] = "指令歷史", ["client.group.hotbar"] = "快捷列", ["client.group.other"] = "其他模組資料",
                ["client.dialog.choose_directory"] = "選擇 Minecraft 遊戲目錄或版本隔離實例", ["client.dialog.reselect_instance"] = "所選目錄下沒有可讀取的客戶端內容。請重新選擇 .minecraft\\versions\\對應版本的實例目錄。", ["client.dialog.no_version"] = "無法從標準版本 JSON 識別 Minecraft 版本和載入器。", ["client.dialog.read_failed"] = "讀取失敗。請確認已選擇有效的 Minecraft 遊戲目錄，並查看執行記錄。", ["client.dialog.read_first"] = "請先選擇並讀取 Minecraft 遊戲目錄。",
                ["client.dialog.format_required"] = "至少需要選擇一種整合包格式。", ["client.dialog.content_required"] = "請至少選擇一個要匯出的內容項目。", ["client.dialog.output_invalid"] = "請填寫有效的輸出目錄和整合包名稱。", ["client.dialog.build_failed"] = "產生客戶端整合包失敗。請檢查網絡、檔案權限和執行記錄。", ["client.dialog.build_failed_detail"] = "部分整合包未能產生：\n\n{0}",
                ["server.title"] = "伺服器一鍵封裝", ["server.subtitle"] = "從遊戲目錄或標準 CF / MR 整合包產生完整可啟動的伺服器 ZIP",
                ["server.source_type"] = "匯入方式", ["server.directory"] = "資料夾", ["server.modpack"] = "整合包",
                ["server.source_path"] = "遊戲目錄", ["server.pack_path"] = "整合包檔案", ["server.choose_directory"] = "選擇目錄", ["server.choose_pack"] = "選擇檔案", ["server.read"] = "讀取內容",
                ["server.drop_title"] = "拖放整合包到這裡", ["server.drop_hint"] = "僅整合包模式支援拖放 .zip 或 .mrpack",
                ["server.source_overview"] = "來源內容", ["server.environment"] = "伺服器環境", ["server.minecraft"] = "Minecraft", ["server.loader"] = "模組載入器", ["server.loader_version"] = "載入器版本", ["server.java"] = "Java 執行環境", ["server.java_hint"] = "讀取內容後會結合遊戲版本及已選模組聲明，自動選擇已安裝的 Java。",
                ["server.version_hint"] = "遊戲版本由匯入內容決定；伺服器一鍵封裝不支援版本遷移。",
                ["server.core"] = "伺服器核心", ["server.core_refresh"] = "重新整理可用核心", ["server.core_none"] = "尚未查詢到可用核心", ["server.core_hint"] = "只顯示官方中繼資料確認支援目前遊戲版本的核心。",
                ["server.content"] = "匯出內容", ["server.mods"] = "模組", ["server.select_all"] = "全選", ["server.clear_all"] = "清除", ["server.mod_name"] = "名稱", ["server.mod_path"] = "相對路徑", ["server.mod_support"] = "伺服器適用性", ["server.mod_source"] = "來源",
                ["server.config"] = "Mod 設定 (config)", ["server.defaultconfigs"] = "預設設定 (defaultconfigs)", ["server.kubejs"] = "KubeJS 腳本與資料", ["server.scripts"] = "腳本目錄 (scripts)",
                ["server.world"] = "伺服器存檔", ["server.no_world"] = "不匯入存檔", ["server.world_hint"] = "所選存檔會完整複製並重新命名為 world。",
                ["server.output"] = "匯出設定", ["server.output_dir"] = "輸出目錄", ["server.output_name"] = "檔案名稱", ["server.browse"] = "瀏覽", ["server.prepare"] = "開始準備", ["server.build"] = "產生伺服器 ZIP",
                ["server.log"] = "執行記錄", ["server.ready"] = "就緒", ["server.reading"] = "正在讀取輸入內容…", ["server.preparing"] = "正在檢查模組並配對伺服器核心…", ["server.building"] = "正在產生伺服器 ZIP…", ["server.prepared"] = "準備完成，可以產生伺服器 ZIP", ["server.cancelled"] = "操作已取消",
                ["server.building_core"] = "正在下載並安裝伺服器核心…", ["server.building_mods_copy"] = "正在複製 MOD…", ["server.building_mods_download"] = "正在下載 MOD…", ["server.building_config"] = "正在複製伺服器設定…", ["server.building_world"] = "正在複製存檔…", ["server.building_files"] = "正在產生伺服器啟動檔案…", ["server.building_archive"] = "正在壓縮伺服器 ZIP…", ["server.download_speed"] = "下載速度：{0}",
                ["server.overview"] = "{0}\n\n來源        {1}\nMinecraft   {2}\n載入器      {3} {4}\n模組        {5} 個\n存檔        {6} 個",
                ["server.support.recommended"] = "建議", ["server.support.optional"] = "可選", ["server.support.unsupported"] = "不支援伺服器", ["server.support.unknown"] = "未知", ["server.origin.manifest"] = "下載清單", ["server.origin.local"] = "本機檔案",
                ["server.dialog.choose_directory"] = "選擇 Minecraft 遊戲目錄或版本隔離實例", ["server.dialog.reselect_instance"] = "所選目錄下沒有可讀取的 mods、config、saves 等內容。請重新選擇 .minecraft\\versions\\對應版本的實例目錄。",
                ["server.dialog.no_version"] = "無法從標準版本 JSON 識別 Minecraft 版本和載入器。", ["server.dialog.quilt"] = "伺服器一鍵封裝暫不支援 Quilt。", ["server.dialog.read_failed"] = "讀取失敗。請確認路徑或整合包格式正確，並查看執行記錄。",
                ["server.dialog.prepare_first"] = "請先讀取內容並完成準備。", ["server.dialog.core_required"] = "請選擇一個目前遊戲版本可用的伺服器核心。", ["server.dialog.source_version_missing"] = "匯入內容中沒有可用的 Minecraft 版本資訊，請重新選擇有效的遊戲目錄或整合包。", ["server.dialog.output_invalid"] = "請填寫有效的輸出目錄和 ZIP 檔案名稱。",
                ["server.dialog.vanilla"] = "該核心為原版核心，此伺服器不可載入任何模組及插件，不能作為模組伺服器使用。是否繼續？", ["server.dialog.eula"] = "是否同意 Minecraft EULA？\n\n選擇「是」會寫入 eula=true；選擇「否」會寫入 eula=false。",
                ["server.dialog.choose_java"] = "選擇用於伺服器的 java.exe", ["server.dialog.java_required"] = "未選擇可用的 Java 執行環境。請重新讀取內容或選擇合適的 Java。", ["server.dialog.java_none"] = "未偵測到可用的 Java。請先安裝 Java {0}，然後重新讀取內容。", ["server.dialog.java_incompatible"] = "Minecraft {0} 及目前已選模組要求使用 Java {1}，目前選擇的是 Java {2}。為避免伺服器啟動失敗，請選擇 Java {1}。",
                ["server.dialog.incompatible"] = "「{0}」存在阻斷兼容性問題：\n\n{1}\n\n是否從輸出中排除此項？\n\n選擇「否」會保留該模組並繼續匯出。",
                ["server.dialog.blocked"] = "伺服器 ZIP 未產生，仍有檔案無法下載或寫入：\n\n{0}", ["server.dialog.build_failed"] = "產生伺服器 ZIP 失敗。請檢查網絡、Java 環境和輸出權限，並查看執行記錄。", ["server.build_complete"] = "伺服器 ZIP 匯出成功", ["server.build_launch_hint"] = "啟動伺服器時，可雙擊 start.bat；亦可右鍵 server-console.ps1 並選擇「使用 PowerShell 執行」，兩者作用相同。控制台會以不同顏色突出警告、錯誤及啟動成功狀態。",
                ["server.version_select_title"] = "選擇遊戲版本", ["server.version_select_hint"] = "此目錄包含多個標準版本 JSON，請選擇要匯出的實例版本。",
                ["agreement.title"] = "用戶協議與使用須知", ["agreement.language"] = "協議語言", ["agreement.code_license"] = "查看程式碼許可（PolyForm NC 1.0.0）", ["agreement.asset_license"] = "查看美術及文件許可（CC BY-NC-SA 4.0）", ["agreement.third_party"] = "查看第三方許可", ["agreement.third_party_title"] = "第三方許可及通知",
                ["agreement.accept"] = "我已閱讀並同意", ["agreement.decline"] = "不同意並退出", ["agreement.close"] = "關閉",
                ["common.ok"] = "確定", ["common.cancel"] = "取消", ["common.yes"] = "是", ["common.no"] = "否",
                ["common.error"] = "錯誤", ["common.warning"] = "提示", ["common.processing"] = "處理中…",
                ["app.unhandled_error"] = "程式遇到未處理的錯誤。\n\n{0}", ["app.agreement_save_failed"] = "無法儲存用戶協議同意狀態，軟件將會退出。\n\n{0}",
                ["dialog.choose_pack"] = "選擇整合包檔案", ["dialog.choose_output"] = "選擇輸出資料夾",
                ["dialog.filter_modpacks"] = "整合包", ["dialog.filter_all"] = "所有檔案",
                ["dialog.invalid_pack"] = "只支援 .zip 或 .mrpack 整合包檔案。", ["dialog.drop_failed"] = "無法讀取拖放的檔案，請使用「選擇檔案」重試並查看運行日誌。", ["dialog.busy"] = "目前正在處理，請稍候。",
                ["dialog.read_first"] = "請先讀取整合包。", ["dialog.target_required"] = "請填寫完整的目標遊戲版本、載入器及載入器版本。",
                ["dialog.analysis_first"] = "產生前請先完成兼容性分析。", ["dialog.overwrite"] = "目標檔案已存在，是否覆蓋？",
                ["dialog.no_loader_version"] = "未能取得相應載入器的穩定版本。", ["dialog.output_is_input"] = "輸出檔案不能覆蓋目前匯入的整合包。",
                ["dialog.output_invalid"] = "請填寫有效的輸出資料夾及檔案名稱。", ["dialog.output_invalid_chars"] = "輸出檔案名稱包含無效字元。",
                ["dialog.read_failed"] = "讀取整合包失敗。請確認檔案沒有損壞且格式正確，並查看運行日誌。", ["dialog.analysis_failed"] = "兼容性分析失敗。請檢查網絡連線後重試，並查看運行日誌。",
                ["dialog.settings_fonts_failed"] = "無法讀取系統字體列表，請稍後重試。", ["dialog.settings_save_failed"] = "設定未能儲存，本次變更可能不會在下次啟動時保留。", ["dialog.agreement_language_save_failed"] = "用戶協議語言偏好未能儲存。", ["dialog.open_folder_failed"] = "無法開啟匯出檔案所在資料夾。",
                ["build.complete"] = "整合包匯出成功", ["build.open_folder"] = "開啟匯出資料夾",
                ["build.notice"] = "整合包匯出成功！可能仍存在部分模組及前置版本衝突或不符合，軟件仍在持續開發中，帶來不便敬請見諒",
                ["build.location"] = "儲存位置：{0}", ["build.failed"] = "產生整合包失敗。請檢查輸出路徑、檔案權限及網絡連線，並查看運行日誌。", ["build.notes"] = "注意事項：",
                ["build.item"] = "{0} [{1}]", ["build.disabled_item"] = "[已停用] {0}",
                ["build.reason.override_collision"] = "{0}（與 overrides 現有檔案同名，未覆蓋原檔案）", ["build.reason.env_scope"] = "{0}（無法保留 env 作用範圍）",
                ["build.warning.cf_override_collision"] = "{0}：目標路徑與 overrides 現有檔案同名，已保留原檔案並使用聯網安裝引用。",
                ["build.warning.mr_override_collision"] = "{0}：目標路徑與 overrides 現有檔案同名，已保留原檔案及聯網安裝引用。",
                ["build.warning.cf_download_fallback"] = "{0}：下載失敗，已回復為 CurseForge 聯網安裝引用。", ["build.warning.cf_no_download"] = "{0}：平台沒有提供下載位址，已保留 CurseForge 聯網安裝引用。",
                ["build.warning.mr_env_reference"] = "{0}：為保留 Modrinth env 作用範圍，已保留聯網安裝引用。", ["build.warning.mr_download_fallback"] = "{0}：下載失敗，已回復為 Modrinth 聯網安裝引用。",
                ["build.warning.disabled_download_preserved"] = "[已停用] {0}：目標下載失敗，已保留舊停用版本。", ["build.warning.disabled_no_target_preserved"] = "[已停用] {0}：未找到目標版本，已保留舊停用版本。",
                ["build.incomplete_status"] = "整合包未匯出",
                ["build.incomplete"] = "整合包未匯出：仍有 {0} 個檔案無法寫入。請排除這些項目或檢查網絡後重試。\n\n{1}",
                ["resolution.not_found"] = "「{0}」沒有相應的目標版本。是否從輸出中排除？\n\n選擇「否」只會暫時忽略，匯出前仍須排除。",
                ["resolution.incompatible"] = "「{0}」存在阻斷兼容性問題：\n\n{1}\n\n是否從輸出中排除此項？",
                ["resolution.duplicate"] = "「{0}」使用了重複輸出路徑「{1}」。是否排除？",
                ["resolution.unmapped"] = "以下阻斷問題無法自動定位到可排除的模組，請返回列表調整選擇後重試：\n\n{0}",
                ["resolution.blocked"] = "仍有 {0} 項阻斷問題未處理。存在阻斷問題時無法匯出。",
                ["deps.title"] = "可能欠缺前置模組", ["deps.body"] = "平台資料顯示可能欠缺以下必要依賴。工具不會自動修改列表，請自行核對：\n\n{0}\n\n此資訊由工具根據平台資料提示，僅供參考。",
                ["deps.entry"] = "{0}（{1}；由 {2} 聲明）", ["deps.more_owners"] = " 等 {0} 個項目", ["deps.more"] = "... 以及其他 {0} 個可能欠缺的前置模組",
                ["status.reading"] = "正在讀取整合包…", ["status.read_ready"] = "已讀取整合包，請確認目標設定後開始分析",
                ["status.searching"] = "正在查詢目標版本…", ["status.analyzing"] = "正在產生兼容性報告…",
                ["status.ready_build"] = "兼容性分析完成，可以產生新整合包", ["status.building"] = "正在產生整合包…",
                ["status.canceling"] = "正在取消…", ["status.cancelled"] = "操作已取消", ["status.analysis_failed"] = "分析失敗，請重試", ["status.loader_fetching"] = "正在取得載入器版本…", ["status.target_changed"] = "遷移目標已變更，請重新分析",
                ["compat.no_issues"] = "未發現可由靜態檢查確認的阻斷或警告。", ["compat.summary"] = "{0} 項阻斷 · {1} 項警告 · {2} 個內容項目",
                ["compat.error"] = "阻斷", ["compat.warning"] = "警告", ["compat.info"] = "資訊",
                ["compat.boundary"] = "邊界", ["compat.static_check"] = "靜態檢查", ["compat.whole"] = "整體", ["compat.pack"] = "整合包", ["compat.pass"] = "通過",
                ["compat.loader_dependency_mismatch"] = "載入器版本不符合模組聲明的依賴要求。",
                ["compat.scope.mod"] = "模組", ["compat.scope.resourcepack"] = "資源包", ["compat.scope.shaderpack"] = "光影包", ["compat.scope.content"] = "內容", ["compat.scope.dependency"] = "依賴", ["compat.scope.output"] = "輸出", ["compat.scope.general"] = "通用",
                ["compat.issue.item_not_found"] = "未找到目標版本檔案。", ["compat.issue.missing_required_dependency"] = "可能欠缺必要前置模組：{0}。",
                ["compat.issue.dependency_version_mismatch"] = "前置模組版本不符合所需範圍。", ["compat.issue.loader_version_mismatch"] = "載入器版本不符合模組要求。", ["compat.issue.loader_dependency_mismatch"] = "載入器版本不符合模組聲明的依賴要求。", ["compat.issue.minecraft_version_mismatch"] = "Minecraft 版本不符合模組要求。",
                ["compat.issue.explicit_incompatibility"] = "與已選項目或目標環境「{0}」明確衝突。", ["compat.issue.explicitly_incompatible_item"] = "平台或模組資料明確標記此項目不兼容。",
                ["compat.issue.duplicate_project"] = "同一平台項目出現多次。", ["compat.issue.duplicate_output_path"] = "多個檔案將寫入相同輸出路徑。",
                ["compat.issue.unsafe_output_path"] = "目標檔案路徑無效或可能超出整合包資料夾。", ["compat.issue.unsafe_override_path"] = "overrides 中存在不安全或大小寫衝突的路徑。", ["compat.issue.override_output_collision"] = "目標檔案與 overrides 中的現有檔案同名；為確保原檔案不變，已阻止覆蓋。",
                ["compat.issue.required_embedded_download_unavailable"] = "此 CurseForge 項目必須嵌入 Modrinth 包，但平台沒有提供可下載位址。", ["compat.issue.required_embedded_scope_unsupported"] = "此 CurseForge 項目必須嵌入，但原 Modrinth 用戶端/伺服器範圍無法安全保留。",
                ["compat.issue.dependency_version_unverified"] = "無法靜態確認依賴版本範圍。", ["compat.issue.incompatibility_version_unverified"] = "無法靜態確認衝突版本範圍。", ["compat.issue.unknown"] = "偵測到未分類的兼容性問題，請查看問題代碼及依據。",
                ["compat.limit.runtime"] = "靜態檢查無法驗證模組位元碼、Mixin、註冊表、資料包及只在執行時出現的衝突。",
                ["compat.limit.relations"] = "只檢查可識別的直接必要依賴、明確衝突及受支援的版本條件；不驗證遞迴依賴或跨平台項目身份。",
                ["compat.limit.metadata"] = "{0} / {1} 個已解析項目欠缺依賴/衝突資料，無法靜態確認其前置及明確衝突。",
                ["compat.limit.java"] = "遷移目標未指定 Java 執行環境版本，因此未檢查模組聲明的 Java 要求。",
                ["compat.limit.artifact"] = "「{0}」的檔案資料不完整：{1}",
                ["compat.limit.artifact_multiple"] = "存在多個「{0}」資料檔案，無法確定應使用哪一個。", ["compat.limit.artifact_read"] = "無法讀取資料檔案「{0}」。", ["compat.limit.artifact_parse"] = "無法解析資料檔案「{0}」。", ["compat.limit.artifact_unknown"] = "資料檢查傳回了未分類警告。",
                ["detail.code"] = "代碼", ["detail.confidence"] = "置信度", ["detail.path"] = "路徑", ["detail.evidence"] = "依據",
                ["log.read_pack"] = "讀取整合包：{0}", ["log.read_complete"] = "讀取完成：format={0}, items={1}, overrides={2}", ["log.read_cancelled"] = "讀取操作已取消",
                ["log.loader_latest"] = "{0} {1} 最新穩定版：{2}", ["log.analysis_start"] = "開始查詢目標：Minecraft {0}, {1}",
                ["log.analysis_complete"] = "目標查詢完成：found={0}, preserved={1}, missing={2}", ["log.analysis_cancelled"] = "分析操作已取消", ["log.build_complete"] = "整合包匯出完成：{0}",
                ["log.excluded"] = "已從輸出排除：{0}", ["log.restored"] = "已恢復到輸出：{0}",
                ["note.preserved"] = "目標環境沒有變更，保留原檔案", ["note.no_cf_key"] = "未設定 CurseForge API Key，已略過備用搜尋",
                ["note.prerelease"] = "只有預發佈版本（{0}）", ["note.project_missing"] = "平台項目或版本不存在",
                ["note.invalid_cf_id"] = "CurseForge 項目 ID 無效", ["note.no_target"] = "原項目沒有可用的目標版本",
                ["note.identity_unverified"] = "無法驗證原項目檔案身份", ["note.no_confident_match"] = "沒有高置信度的平台身份配對",
                ["note.no_main_file"] = "目標版本欠缺可用主檔案"
            },
            ["en_US"] = new Dictionary<string, string>
            {
                ["app.name"] = "MC Modpack Tool", ["app.subtitle"] = "Minecraft Modpack Workbench", ["app.short_subtitle"] = "Workbench",
                ["window.minimize"] = "Minimize", ["window.maximize_restore"] = "Maximize or restore", ["window.close"] = "Close",
                ["nav.home"] = "Home", ["nav.migration"] = "Version Migration", ["nav.client_pack"] = "Client Modpack Builder", ["nav.server"] = "One-click Server Pack", ["nav.settings"] = "Settings",
                ["sidebar.collapse"] = "Collapse sidebar", ["sidebar.expand"] = "Expand sidebar",
                ["home.title"] = "MC Modpack Tool", ["home.subtitle"] = "Choose a module to start working with a modpack",
                ["home.migration"] = "Modpack Version Migration", ["home.migration.desc"] = "Match a CurseForge or Modrinth pack to a target game version",
                ["home.client_pack"] = "Client Modpack Builder", ["home.client_pack.desc"] = "Export a Minecraft game directory as an installable CF / MR client modpack",
                ["home.server"] = "One-click Server Pack", ["home.server.desc"] = "Export a game directory or CF / MR modpack as a runnable server ZIP",
                ["home.agreement"] = "User Agreement", ["home.bilibili"] = "Bilibili Profile", ["home.github"] = "GitHub", ["author"] = "Author: FengchenWD",
                ["home.creator"] = "FengchenWD", ["home.creator_desc"] = "Minecraft/gaming creator and software developer",
                ["migration.title"] = "Modpack Version Migration", ["migration.subtitle"] = "Automatic CF/MR modpack game version conversion",
                ["migration.pack_file"] = "Modpack File", ["migration.choose_file"] = "Choose File", ["migration.read_pack"] = "Read Modpack",
                ["migration.drop_title"] = "Drop a modpack here", ["migration.drop_hint"] = "Supports .zip and .mrpack; the file will be read automatically",
                ["migration.source_overview"] = "Source Overview", ["migration.target"] = "Migration Target", ["migration.loader"] = "Loader",
                ["migration.loader_version"] = "Loader Version", ["migration.latest_loader"] = "Get Latest Stable",
                ["migration.output_dir"] = "Output Folder", ["migration.browse"] = "Browse", ["migration.output_name"] = "File / Pack Name",
                ["migration.check"] = "Start Analysis", ["migration.analysis_hint"] = "Import and read the full modpack, then start analysis here.",
                ["migration.overview"] = "{0}\n\nFormat       {1}\nMinecraft    {2}\nLoader       {3} {4}\nContent      {5} mods · {6} resource packs · {7} shader packs\nPreserved    Everything under overrides (not queried, migrated, or rewritten)",
                ["migration.report"] = "Compatibility Report", ["migration.report_hint"] = "Read a modpack, then run a compatibility check",
                ["migration.refresh"] = "Analyze Again", ["migration.files"] = "File Details", ["migration.log"] = "Activity Log",
                ["migration.ready"] = "Ready", ["migration.build"] = "Build New Modpack",
                ["migration.new_pack"] = "New Modpack", ["migration.migrated_suffix"] = " (Migrated)",
                ["tree.severity"] = "Severity", ["tree.category"] = "Category", ["tree.item"] = "Item", ["tree.conclusion"] = "Result",
                ["tree.name"] = "Name", ["tree.source"] = "Source", ["tree.status"] = "Status", ["tree.output"] = "Output",
                ["category.mod"] = "Mod", ["category.resourcepack"] = "Resource Pack", ["category.shaderpack"] = "Shader Pack",
                ["item_status.found"] = "Matched", ["item_status.not_found"] = "Not Found", ["item_status.preserved"] = "Preserved", ["item_status.pending"] = "Pending Analysis",
                ["item_status.passthrough"] = "Transferred As-Is", ["item_status.excluded"] = "Excluded", ["item_status.disabled"] = "Disabled", ["item_status.warning"] = "Warning",
                ["action.exclude"] = "Exclude", ["action.restore"] = "Restore", ["action.open"] = "Open Page",
                ["action.exclude_prompt"] = "Exclude “{0}” from the output?", ["action.exclude_title"] = "Exclude Content Item",
                ["settings.title"] = "Settings", ["settings.subtitle"] = "Changes apply immediately and are saved automatically",
                ["settings.language"] = "Language", ["settings.language_desc"] = "Choose the language used by the application interface.",
                ["settings.appearance"] = "Appearance", ["settings.appearance_desc"] = "Choose light, dark, or follow the system theme.",
                ["settings.light"] = "Light", ["settings.dark"] = "Dark", ["settings.system"] = "Follow System",
                ["settings.accent"] = "Accent Color", ["settings.accent_desc"] = "Choose the accent used for buttons, the sidebar, and selections.",
                ["settings.custom_color"] = "Custom Color", ["settings.system_palette"] = "Open System Color Picker", ["settings.color_rgb_invalid"] = "{0} must be an integer from 0 to 255. Please enter it again.", ["settings.color_hex_invalid"] = "Invalid HEX color. Enter a value such as #167D6A.", ["settings.reset_color"] = "Reset",
                ["settings.font"] = "Interface Font", ["settings.font_desc"] = "Choose from fonts installed on this computer.", ["settings.default_font"] = "System Default", ["settings.font_preview"] = "MC Modpack Tool · Minecraft 1.21.1",
                ["settings.about"] = "About", ["settings.version"] = "Version", ["settings.check_updates"] = "Check for Updates", ["settings.update_unavailable"] = "The update service is not available yet.",
                ["client.title"] = "Client Modpack Builder", ["client.subtitle"] = "Create a standard CurseForge / Modrinth client modpack from a Minecraft game directory",
                ["client.source_path"] = "Game directory", ["client.choose_directory"] = "Choose folder", ["client.read"] = "Read content",
                ["client.source_hint"] = "Folder import only. Choose a game directory or isolated instance containing mods, config, saves, and related content.",
                ["client.source_overview"] = "Directory overview", ["client.environment"] = "Client environment", ["client.loader"] = "Mod loader",
                ["client.content"] = "Export content", ["client.content_hint"] = "A parent checkbox controls its whole group. Directory items are copied in full without listing every internal file.",
                ["client.restore_defaults"] = "Restore defaults", ["client.clear_all"] = "Clear all",
                ["client.output"] = "Export settings", ["client.formats"] = "Modpack formats", ["client.output_dir"] = "Output folder", ["client.output_name"] = "Modpack name", ["client.browse"] = "Browse",
                ["client.log"] = "Activity log", ["client.ready"] = "Ready", ["client.reading"] = "Reading client content…", ["client.read_ready"] = "Content read; select items and create the modpack", ["client.path_changed"] = "The input path changed; read the content again", ["client.cancelled"] = "Operation cancelled",
                ["client.build"] = "Create client modpack", ["client.building"] = "Creating client modpack…", ["client.building_match"] = "Matching CF / MR downloads by exact file hash…", ["client.building_copy"] = "Copying local content and unmatched files…", ["client.building_manifest"] = "Writing the modpack manifest…", ["client.building_archive"] = "Compressing the modpack…", ["client.build_complete"] = "Client modpack exported successfully", ["client.build_partial"] = "Some formats were exported; other formats failed",
                ["client.overview"] = "{0}\n\nMinecraft    {1}\nLoader       {2} {3}\nContent      {4} items\nSelected     {5} items",
                ["client.group_summary"] = "{0} item(s) · {1}", ["client.group.expand"] = "Expand this category", ["client.group.collapse"] = "Collapse this category",
                ["client.group.mod"] = "Mods", ["client.group.resource_pack"] = "Resource packs", ["client.group.shader_pack"] = "Shader packs", ["client.group.world"] = "Worlds and maps",
                ["client.group.configuration"] = "Mod and game configuration", ["client.group.mod_data"] = "Minimap, world map, and other mod data", ["client.group.options"] = "Game options (options.txt)", ["client.group.server_list"] = "Multiplayer server list",
                ["client.group.screenshot"] = "Screenshots", ["client.group.structure"] = "Schematics and structures", ["client.group.replay"] = "Recordings and replays", ["client.group.command_history"] = "Command history", ["client.group.hotbar"] = "Saved hotbar", ["client.group.other"] = "Other mod data",
                ["client.dialog.choose_directory"] = "Choose a Minecraft game directory or isolated instance", ["client.dialog.reselect_instance"] = "The selected directory has no readable client content. Select the corresponding .minecraft\\versions\\<instance> directory instead.", ["client.dialog.no_version"] = "No Minecraft version and loader could be identified from a standard version JSON.", ["client.dialog.read_failed"] = "Reading failed. Choose a valid Minecraft game directory and review the activity log.", ["client.dialog.read_first"] = "Choose and read a Minecraft game directory first.",
                ["client.dialog.format_required"] = "Select at least one modpack format.", ["client.dialog.content_required"] = "Select at least one content item to export.", ["client.dialog.output_invalid"] = "Enter a valid output folder and modpack name.", ["client.dialog.build_failed"] = "Creating the client modpack failed. Check the network, file permissions, and activity log.", ["client.dialog.build_failed_detail"] = "Some modpacks could not be created:\n\n{0}",
                ["server.title"] = "One-click Server Pack", ["server.subtitle"] = "Create a complete runnable server ZIP from a game directory or standard CF / MR modpack",
                ["server.source_type"] = "Import type", ["server.directory"] = "Folder", ["server.modpack"] = "Modpack",
                ["server.source_path"] = "Game directory", ["server.pack_path"] = "Modpack file", ["server.choose_directory"] = "Choose folder", ["server.choose_pack"] = "Choose file", ["server.read"] = "Read content",
                ["server.drop_title"] = "Drop a modpack here", ["server.drop_hint"] = "Only modpack mode accepts dropped .zip or .mrpack files",
                ["server.source_overview"] = "Source content", ["server.environment"] = "Server environment", ["server.minecraft"] = "Minecraft", ["server.loader"] = "Mod loader", ["server.loader_version"] = "Loader version", ["server.java"] = "Java runtime", ["server.java_hint"] = "Installed Java is selected from the game version and the requirements declared by selected mods.",
                ["server.version_hint"] = "The game version is fixed by the imported content; one-click server packaging does not migrate versions.",
                ["server.core"] = "Server core", ["server.core_refresh"] = "Refresh available cores", ["server.core_none"] = "No available core has been queried", ["server.core_hint"] = "Only cores confirmed by official metadata for this game version are shown.",
                ["server.content"] = "Export content", ["server.mods"] = "Mods", ["server.select_all"] = "Select all", ["server.clear_all"] = "Clear", ["server.mod_name"] = "Name", ["server.mod_path"] = "Relative path", ["server.mod_support"] = "Server support", ["server.mod_source"] = "Source",
                ["server.config"] = "Mod config (config)", ["server.defaultconfigs"] = "Default config (defaultconfigs)", ["server.kubejs"] = "KubeJS scripts and data", ["server.scripts"] = "Scripts directory",
                ["server.world"] = "Server world", ["server.no_world"] = "Do not import a world", ["server.world_hint"] = "The selected save is copied completely and renamed to world.",
                ["server.output"] = "Export settings", ["server.output_dir"] = "Output folder", ["server.output_name"] = "File name", ["server.browse"] = "Browse", ["server.prepare"] = "Prepare", ["server.build"] = "Create server ZIP",
                ["server.log"] = "Run log", ["server.ready"] = "Ready", ["server.reading"] = "Reading input content…", ["server.preparing"] = "Checking mods and resolving server cores…", ["server.building"] = "Creating server ZIP…", ["server.prepared"] = "Preparation complete; the server ZIP can be created", ["server.cancelled"] = "Operation cancelled",
                ["server.building_core"] = "Downloading and installing the server core…", ["server.building_mods_copy"] = "Copying mods…", ["server.building_mods_download"] = "Downloading mods…", ["server.building_config"] = "Copying server configuration…", ["server.building_world"] = "Copying the world…", ["server.building_files"] = "Writing server launch files…", ["server.building_archive"] = "Compressing the server ZIP…", ["server.download_speed"] = "Download speed: {0}",
                ["server.overview"] = "{0}\n\nSource       {1}\nMinecraft    {2}\nLoader       {3} {4}\nMods         {5}\nWorlds       {6}",
                ["server.support.recommended"] = "Recommended", ["server.support.optional"] = "Optional", ["server.support.unsupported"] = "Server unsupported", ["server.support.unknown"] = "Unknown", ["server.origin.manifest"] = "Download manifest", ["server.origin.local"] = "Local file",
                ["server.dialog.choose_directory"] = "Choose a Minecraft game directory or isolated instance", ["server.dialog.reselect_instance"] = "The selected directory has no readable mods, config, saves, or related content. Select the corresponding .minecraft\\versions\\<instance> directory instead.",
                ["server.dialog.no_version"] = "No Minecraft version and loader could be identified from a standard version JSON.", ["server.dialog.quilt"] = "One-click server packaging does not support Quilt.", ["server.dialog.read_failed"] = "Reading failed. Check the path or modpack format and review the run log.",
                ["server.dialog.prepare_first"] = "Read the content and complete preparation first.", ["server.dialog.core_required"] = "Select a server core available for the current game version.", ["server.dialog.source_version_missing"] = "The imported content does not contain a usable Minecraft version. Select a valid game directory or modpack.", ["server.dialog.output_invalid"] = "Enter a valid output folder and ZIP file name.",
                ["server.dialog.vanilla"] = "This is a vanilla core. It cannot load any mods or plugins and cannot be used as a modded server. Continue?", ["server.dialog.eula"] = "Do you agree to the Minecraft EULA?\n\nYes writes eula=true; No writes eula=false.",
                ["server.dialog.choose_java"] = "Choose java.exe for the server", ["server.dialog.java_required"] = "No usable Java runtime is selected. Read the content again or select a suitable Java runtime.", ["server.dialog.java_none"] = "No usable Java runtime was detected. Install Java {0}, then read the content again.", ["server.dialog.java_incompatible"] = "Minecraft {0} and the selected mods require Java {1}, but Java {2} is selected. Select Java {1} to avoid server startup failures.",
                ["server.dialog.incompatible"] = "“{0}” has a blocking compatibility issue:\n\n{1}\n\nExclude this item from the output?\n\nChoosing No keeps this mod and continues the export.",
                ["server.dialog.blocked"] = "The server ZIP was not created because files could not be downloaded or written:\n\n{0}", ["server.dialog.build_failed"] = "Creating the server ZIP failed. Check the network, Java environment, output permissions, and run log.", ["server.build_complete"] = "Server ZIP exported successfully", ["server.build_launch_hint"] = "To start the server, double-click start.bat, or right-click server-console.ps1 and choose Run with PowerShell. Both perform the same action. The console highlights warnings, errors, and successful startup states with distinct colors.",
                ["server.version_select_title"] = "Choose game version", ["server.version_select_hint"] = "This directory contains multiple standard version JSON files. Choose the instance version to export.",
                ["agreement.title"] = "User Agreement and Important Information", ["agreement.language"] = "Agreement Language", ["agreement.code_license"] = "View Code License (PolyForm NC 1.0.0)", ["agreement.asset_license"] = "View Art & Documentation License (CC BY-NC-SA 4.0)", ["agreement.third_party"] = "View Third-Party Licenses", ["agreement.third_party_title"] = "Third-Party Licenses and Notices",
                ["agreement.accept"] = "I Have Read and Agree", ["agreement.decline"] = "Decline and Exit", ["agreement.close"] = "Close",
                ["common.ok"] = "OK", ["common.cancel"] = "Cancel", ["common.yes"] = "Yes", ["common.no"] = "No",
                ["common.error"] = "Error", ["common.warning"] = "Notice", ["common.processing"] = "Working…",
                ["app.unhandled_error"] = "The application encountered an unhandled error.\n\n{0}", ["app.agreement_save_failed"] = "The agreement acceptance could not be saved. The application will exit.\n\n{0}",
                ["dialog.choose_pack"] = "Choose Modpack File", ["dialog.choose_output"] = "Choose Output Folder",
                ["dialog.filter_modpacks"] = "Modpacks", ["dialog.filter_all"] = "All Files",
                ["dialog.invalid_pack"] = "Only .zip and .mrpack modpack files are supported.", ["dialog.drop_failed"] = "The dropped file could not be read. Use Choose File to try again and review the Activity Log.", ["dialog.busy"] = "An operation is already in progress.",
                ["dialog.read_first"] = "Read a modpack first.", ["dialog.target_required"] = "Enter the target game version, loader, and loader version.",
                ["dialog.analysis_first"] = "Complete compatibility analysis before building.", ["dialog.overwrite"] = "The destination already exists. Replace it?",
                ["dialog.no_loader_version"] = "No stable version was found for that loader.", ["dialog.output_is_input"] = "The output file cannot overwrite the imported modpack.",
                ["dialog.output_invalid"] = "Enter a valid output folder and file name.", ["dialog.output_invalid_chars"] = "The output file name contains invalid characters.",
                ["dialog.read_failed"] = "The modpack could not be read. Confirm that the file is valid and not damaged, then review the Activity Log.", ["dialog.analysis_failed"] = "Compatibility analysis failed. Check the network connection, try again, and review the Activity Log.",
                ["dialog.settings_fonts_failed"] = "The system font list could not be loaded. Try again later.", ["dialog.settings_save_failed"] = "Settings could not be saved; this change may not persist after restart.", ["dialog.agreement_language_save_failed"] = "The agreement language preference could not be saved.", ["dialog.open_folder_failed"] = "The folder containing the exported file could not be opened.",
                ["build.complete"] = "Modpack Exported", ["build.open_folder"] = "Open Export Folder",
                ["build.notice"] = "The modpack was exported successfully. Some mod or dependency version conflicts may remain. This application is still in development; thank you for your understanding.",
                ["build.location"] = "Saved to: {0}", ["build.failed"] = "The modpack could not be exported. Check the output path, file permissions, and network connection, then review the Activity Log.", ["build.notes"] = "Notes:",
                ["build.item"] = "{0} [{1}]", ["build.disabled_item"] = "[Disabled] {0}",
                ["build.reason.override_collision"] = "{0} (an overrides file has the same name; the existing file was not overwritten)", ["build.reason.env_scope"] = "{0} (the env scope could not be preserved)",
                ["build.warning.cf_override_collision"] = "{0}: an overrides file has the same target path; the existing file and online-install reference were preserved.",
                ["build.warning.mr_override_collision"] = "{0}: an overrides file has the same target path; the existing file and remote reference were preserved.",
                ["build.warning.cf_download_fallback"] = "{0}: the download failed; a CurseForge online-install reference was used instead.", ["build.warning.cf_no_download"] = "{0}: the platform did not provide a download URL; the CurseForge online-install reference was preserved.",
                ["build.warning.mr_env_reference"] = "{0}: the remote Modrinth reference was preserved to keep its env scope.", ["build.warning.mr_download_fallback"] = "{0}: the download failed; the Modrinth remote reference was used instead.",
                ["build.warning.disabled_download_preserved"] = "[Disabled] {0}: the target download failed; the old disabled version was preserved.", ["build.warning.disabled_no_target_preserved"] = "[Disabled] {0}: no target version was found; the old disabled version was preserved.",
                ["build.incomplete_status"] = "Modpack Not Exported",
                ["build.incomplete"] = "The modpack was not exported because {0} file(s) could not be written. Exclude those items or check the network and try again.\n\n{1}",
                ["resolution.not_found"] = "No target version is available for “{0}”. Exclude it from the output?\n\nChoosing No only postpones the decision; it must be excluded before export.",
                ["resolution.incompatible"] = "“{0}” has a blocking compatibility issue:\n\n{1}\n\nExclude this item from the output?",
                ["resolution.duplicate"] = "“{0}” uses the duplicate output path “{1}”. Exclude it?",
                ["resolution.unmapped"] = "These blocking issues could not be mapped to a mod that can be excluded. Adjust the list and try again:\n\n{0}",
                ["resolution.blocked"] = "{0} blocking issue(s) remain. Export cannot continue until they are resolved.",
                ["deps.title"] = "Possible Missing Dependencies", ["deps.body"] = "Platform metadata suggests that these required dependencies may be missing. The tool will not change the list automatically; review them yourself:\n\n{0}\n\nThis notice is generated from platform metadata and is for reference only.",
                ["deps.entry"] = "{0} ({1}; declared by {2})", ["deps.more_owners"] = " and {0} more items", ["deps.more"] = "... and {0} more potentially missing dependencies",
                ["status.reading"] = "Reading modpack…", ["status.read_ready"] = "Modpack read; confirm the target and start analysis",
                ["status.searching"] = "Looking up target versions…", ["status.analyzing"] = "Creating compatibility report…",
                ["status.ready_build"] = "Compatibility analysis complete; the pack can be built", ["status.building"] = "Building modpack…",
                ["status.canceling"] = "Canceling…", ["status.cancelled"] = "Operation canceled", ["status.analysis_failed"] = "Analysis failed; try again", ["status.loader_fetching"] = "Getting loader version…", ["status.target_changed"] = "The migration target changed; run analysis again",
                ["compat.no_issues"] = "No statically confirmed blockers or warnings were found.", ["compat.summary"] = "{0} blockers · {1} warnings · {2} content items",
                ["compat.error"] = "Blocking", ["compat.warning"] = "Warning", ["compat.info"] = "Information",
                ["compat.boundary"] = "Boundary", ["compat.static_check"] = "Static analysis", ["compat.whole"] = "Overall", ["compat.pack"] = "Modpack", ["compat.pass"] = "Pass",
                ["compat.loader_dependency_mismatch"] = "The loader version does not satisfy the dependency declared by this mod.",
                ["compat.scope.mod"] = "Mod", ["compat.scope.resourcepack"] = "Resource Pack", ["compat.scope.shaderpack"] = "Shader Pack", ["compat.scope.content"] = "Content", ["compat.scope.dependency"] = "Dependency", ["compat.scope.output"] = "Output", ["compat.scope.general"] = "General",
                ["compat.issue.item_not_found"] = "No file was found for the target version.", ["compat.issue.missing_required_dependency"] = "A required dependency may be missing: {0}.",
                ["compat.issue.dependency_version_mismatch"] = "The dependency version does not satisfy the required range.", ["compat.issue.loader_version_mismatch"] = "The loader version does not satisfy this mod's requirement.", ["compat.issue.loader_dependency_mismatch"] = "The loader version does not satisfy the dependency declared by this mod.", ["compat.issue.minecraft_version_mismatch"] = "The Minecraft version does not satisfy this mod's requirement.",
                ["compat.issue.explicit_incompatibility"] = "Explicitly conflicts with the selected item or target environment “{0}”.", ["compat.issue.explicitly_incompatible_item"] = "Platform or mod metadata explicitly marks this item as incompatible.",
                ["compat.issue.duplicate_project"] = "The same platform project appears more than once.", ["compat.issue.duplicate_output_path"] = "Multiple files will be written to the same output path.",
                ["compat.issue.unsafe_output_path"] = "The target path is invalid or may escape the modpack directory.", ["compat.issue.unsafe_override_path"] = "An overrides path is unsafe or conflicts by letter case.", ["compat.issue.override_output_collision"] = "The target file has the same name as an existing overrides file; overwrite was blocked to preserve it.",
                ["compat.issue.required_embedded_download_unavailable"] = "This CurseForge item must be embedded in a Modrinth pack, but no download URL is available.", ["compat.issue.required_embedded_scope_unsupported"] = "This CurseForge item must be embedded, but its original Modrinth client/server scope cannot be preserved safely.",
                ["compat.issue.dependency_version_unverified"] = "The dependency version range could not be verified statically.", ["compat.issue.incompatibility_version_unverified"] = "The incompatible version range could not be verified statically.", ["compat.issue.unknown"] = "An unclassified compatibility issue was detected; review its code and evidence.",
                ["compat.limit.runtime"] = "Static analysis cannot inspect mod bytecode, mixins, registries, datapacks, or runtime-only conflicts.",
                ["compat.limit.relations"] = "Only recognized direct required dependencies, explicit conflicts, and supported version predicates are checked; recursive dependencies and cross-platform identity mapping are not verified.",
                ["compat.limit.metadata"] = "Dependency/conflict metadata was absent for {0} of {1} resolved items, so their requirements and explicit conflicts cannot be confirmed statically.",
                ["compat.limit.java"] = "Java requirements declared by mods were not checked because the migration target does not include a Java runtime version.",
                ["compat.limit.artifact"] = "Artifact metadata for “{0}” was incomplete: {1}",
                ["compat.limit.artifact_multiple"] = "Multiple “{0}” metadata files were found, so the correct one is ambiguous.", ["compat.limit.artifact_read"] = "The metadata file “{0}” could not be read.", ["compat.limit.artifact_parse"] = "The metadata file “{0}” could not be parsed.", ["compat.limit.artifact_unknown"] = "The metadata check returned an unclassified warning.",
                ["detail.code"] = "Code", ["detail.confidence"] = "Confidence", ["detail.path"] = "Path", ["detail.evidence"] = "Evidence",
                ["log.read_pack"] = "Reading modpack: {0}", ["log.read_complete"] = "Read complete: format={0}, items={1}, overrides={2}", ["log.read_cancelled"] = "Read operation cancelled",
                ["log.loader_latest"] = "Latest stable {0} {1}: {2}", ["log.analysis_start"] = "Resolving target: Minecraft {0}, {1}",
                ["log.analysis_complete"] = "Target resolution complete: found={0}, preserved={1}, missing={2}", ["log.analysis_cancelled"] = "Analysis cancelled", ["log.build_complete"] = "Modpack export complete: {0}",
                ["log.excluded"] = "Excluded from output: {0}", ["log.restored"] = "Restored to output: {0}",
                ["note.preserved"] = "The target environment is unchanged; the original file will be preserved", ["note.no_cf_key"] = "No CurseForge API key is configured; fallback search was skipped",
                ["note.prerelease"] = "Only a prerelease is available ({0})", ["note.project_missing"] = "The platform project or version does not exist",
                ["note.invalid_cf_id"] = "The CurseForge project ID is invalid", ["note.no_target"] = "The original project has no compatible target version",
                ["note.identity_unverified"] = "The original project file identity could not be verified", ["note.no_confident_match"] = "No high-confidence platform identity match was found",
                ["note.no_main_file"] = "The target version has no usable primary file"
            }
        };
}
